### ISSUE TITLE
Blank space appearing when switching between tabs on doc page

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/docs#1007]
### What You Are Seeing?

Switching between tabs on a docset causing weird rendering

<img width="1062" alt="image" src="https://github.com/chocolatey/docs/assets/8674240/8a465e0d-07c2-48b9-a60d-91f6ddc877b0">

### What is Expected?

The switch is seamless and does not cause unnecessary blank space

### How Did You Get This To Happen? (Steps to Reproduce)

1. Visit https://docs.chocolatey.org/en-us/central-management/setup/database/#database-authentication-scenarios
2. Switch between the 4 scenario tabs

**Comment by st3phhays** [comment]
This appears to be a problem with too much CSS being purged on the build process. I'll need to add some classes to the safelist in choco-theme so they will not be purged.
