### ISSUE TITLE
Chat doesn't hide right menu when it flies out

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/docs#101]
### What are you seeing?
When I open chat, it doesn't hide all of the page where it comes in.

### What is expected?
The chat should cover the right menu.

### Repro

1. Go to any page (https://docs.chocolatey.org/en-us/why)
2. Click on "Open Chat" in the bottom right.
3. See image below

![image](https://user-images.githubusercontent.com/63502/102392552-d2dbcb80-3f9c-11eb-8076-7bb1f9eea81f.png)

**Comment by designxsteph** [comment]
Ah! Thats a new one. I'll get it fixed up.
