### ISSUE TITLE
formatting broken

### ISSUE THREAD

**Issue by stefan-wenig** [chocolatey/docs#107]
The commit https://github.com/chocolatey/docs/commit/18f4f36827f3527a3e2e90ffaa3b8220cb119780 "(maint) General formatting updates" broke some formatting.
It replaced all **note** occurences with :memo: style notes, even if they were mid sentence. As a result, they became unreadable.
e.g. https://github.com/chocolatey/docs/blame/18f4f36827f3527a3e2e90ffaa3b8220cb119780/input/en-us/information/security.md#L32

**Comment by vexx32** [comment]
This is what I'm seeing currently for the linked section.
![image](https://user-images.githubusercontent.com/32407840/102717270-391f6180-42af-11eb-93fd-80d339d13a59.png)

At least for me, that reads okay? Was there another occurrence elsewhere that shows it better?

**Comment by designxsteph** [comment]
I think in this case a `)` needs added after 'Virus Total' and the `)` needs removed on the end of the note call out. Perhaps?

**Comment by gep13** [comment]
@stefan-wenig thank you for taking the time to raise this issue, and for tracking down the cause of it.

I have just pushed up a commit that I believe addresses the problem, and which should go live on the site soon.  If you are still seeing a problem, please let us know, and we can investigate further.  Or if you would like to submit a PR to fix the issue, we can get that reviewed.
