### ISSUE TITLE
Malformed header in troubleshooting.md & clarity around creating PS profile if it doesn't exist

### ISSUE THREAD

**Issue by vexx32** [chocolatey/docs#109]
https://docs.chocolatey.org/en-us/troubleshooting#why-does-choco-in

Looks like this heading is supposed to say `why does choco in{tab} not work for me?` but the `{tab}` is being interpreted in an odd way.

What's the proper way to escape this in the markdown? Just use HTML `&code;` for it?

---

Also, per https://github.com/chocolatey/choco/issues/1971, we need to clarify a few details in this answer, particularly around creating the PS profile if it doesn't exist.

**Comment by gep13** [comment]
Currently, the site renders as this:

![image](https://user-images.githubusercontent.com/1271146/102755850-e608e580-4366-11eb-9da2-2bb878bf791b.png)

**Comment by gep13** [comment]
@vexx32 thanks for noticing this, and raising this issue.  I have addressed the problem, and this should now show as the following:

![image](https://user-images.githubusercontent.com/1271146/102756040-32ecbc00-4367-11eb-9d8f-c0233be0a5c4.png)
