### ISSUE TITLE
Create fragment for WSUS configuration

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/docs#117]
See https://docs.chocolatey.org/en-us/guides/organizations/set-up-chocolatey-server#configure-simple-server-alongside-wsus-admin-site

This information is applicable when running Chocolatey Simple.Server, _as well as_ Central Management on a server that also has the WSUS role installed. Creating a slug would make maintaining this information in 2 places more manageable.

**Comment by gep13** [comment]
@steviecoaster can you help me understand what you mean be `slug` here?

**Comment by gep13** [comment]
Had a chat with @steviecoaster about this, and `slug` was referring to the concept of a shared markdown fragment, which would mean that the same file can be used in multiple places, rather than duplicating the information.
