### ISSUE TITLE
QDE Setup: OVF is available, not OVA

### ISSUE THREAD

**Issue by adilio** [chocolatey/docs#138]
The following page and section for QDE OVF Setup as an OVA/OVF:

https://docs.chocolatey.org/en-us/quick-deployment/setup/#platform-vmware-other-ovfova-template

We _do not_ currently provide an OVA compliant with the standardized Open Virtual Appliance format, therefore we should not refer this format directly here. This is more of a small clarity fix.

**Comment by pauby** [comment]
Will the changes that are being made not provide that compliant image?

**Comment by adilio** [comment]
We don't know exactly when that will become available, as the amount of work required to create a platform-agnostic OVA is non-trivial.

Until that's available, we don't want this information to be misleading for anyone expecting that to be available.

It's a real small change, but I would rather be clear so as not to build that incorrect expectation.

**Comment by adilio** [comment]
Hi @pauby, as there's been no change to this since February, would you say it's safe to go ahead and submit a PR for this change?

**Comment by pauby** [comment]
Yeah, go for it!
