### ISSUE TITLE
Links to validation and verifier

### ISSUE THREAD

**Issue by ForNeVeR** [chocolatey/docs#151]
[This page](https://docs.chocolatey.org/en-us/community-repository/moderation/) has links to [package-validator](https://github.com/chocolatey/package-validator) (archived) and [package-verifier](https://github.com/chocolatey/package-verifier) (deleted) GitHub repositories.  The links should probably be replaced by something less outdated.

**Comment by gep13** [comment]
@ForNeVeR thanks for pointing these out.  I have updated the links.

Let us know if you find anything else that isn't quite right, or if you can, you can edit the page with the link on the top right of each page:

![image](https://user-images.githubusercontent.com/1271146/111035323-d521ba80-8411-11eb-86c4-af3e5984dcb1.png)
