### ISSUE TITLE
Chocolatey Agent requirements update

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/docs#157]
We need to document the requirement for Logon As Service and Logon as Batch rights to be given to the account used to run the chocolatey-agent service.

**Comment by ryanrichter94** [comment]
Current place in docs this is referenced https://docs.chocolatey.org/en-us/agent/setup#package-parameters

**Comment by ryanrichter94** [comment]
Needs a blurb in requirements with something like this:

“The Chocolatey Agent Service requires Log On As Service and Log On As Batch rights. We attempt to set these rights on the user at the time of installation via Local Policy, but if you have a restrictive Group Policy that will be applied to the system, please ensure that the user account you are attempting to use (or ChocolateyLocalAdmin as the default) has the correct permissions applied in your Group Policy”
