### ISSUE TITLE
Add --no-progress to CCM Prereqs installs

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/docs#178]
See https://docs.chocolatey.org/en-us/central-management/setup/website for example.

It's kind of annoying to see all the progress. We should add `--no-progress` here.

**Comment by vexx32** [comment]
Annoying in what respect? It tends to be clutter in log files in automation, but if end users are running it directly, they'd probably want to see the progress, no?

**Comment by steviecoaster** [comment]
I was on a customer call and they complained. Hence raising the issue. :)

**Comment by adilio** [comment]
A couple more users have reported this to me as well, recently. We should probably prioritize this.
