### ISSUE TITLE
Setup / Install References Missing CMD File

### ISSUE THREAD

**Issue by Windos** [chocolatey/docs#186]
Hey Team, the [Setup / Install](https://docs.chocolatey.org/en-us/choco/setup#install-using-powershell-from-cmd.exe) ([md](https://github.com/chocolatey/docs/blame/master/input/en-us/choco/setup.md#L612)) docs reference a [CMD file](https://chocolatey.org/installchocolatey.cmd) that appears to have move or no longer exists.

Link should be updated or removed.

**Comment by Windos** [comment]
Per @JPRuskin:

> For the Cmd file, that appears to be case sensitive - try https://chocolatey.org/installChocolatey.cmd.

**Comment by JPRuskin** [comment]
Updating the link now.
