### ISSUE TITLE
Update Nexus Upgrade QDE Docs Page

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/docs#194]
## Explanation of Work Needing Done
Need to go through and update the script on the nexus upgrade doc for QDE since the latest version of the nexus package on the CCR has package parameters for `--params "'/BackupSslConfig'"`. Waiting for next version after V3.30.1-01 since this specific version has a bug when invoked in powershell with the connection test looping in shell. This next version as of writing this is current goin through the package moderation process.

 ### References
 * [ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/10776)

**Comment by ryanrichter94** [comment]
A PR has been merged to address this issue.

**Comment by gep13** [comment]
PR that was created is #251
