### ISSUE TITLE
QDE in Azure documentation should have a guide to accessing VM via RDP

### ISSUE THREAD

**Issue by JPRuskin** [chocolatey/docs#242]
Documentation covering how to connect to the VM via RDP was requested, as the process is more complex than it might be - and it's unrealistic to hope that customers won't need to connect.

### What am I seeing?
A lack of documentation for this purpose.

### What is expected?
Documentation showing a user how to connect to a QDE in Azure environment with RDP, such that they can make changes to the VM.

**Comment by ryanrichter94** [comment]
Closing this off as PR #243 has been merged to add this documentation.
