### ISSUE TITLE
Implement Gulp

### ISSUE THREAD

**Issue by designxsteph** [chocolatey/docs#26]
Things Gulp can help with:

* Bundle and minify css/js
* Drastically reduce the css footprint by removing unused css from framework libraries (such as bootstrap)
* Pull in libraries needed on build instead of storing copies
* Make upgrading/maintaining libraries easier/faster
* Generating PDF files from docs

Surely there are more, but overall I feel like this would be a great addition to add to the build process.

**Comment by gep13** [comment]
@designxsteph I have just added a new [commit](https://github.com/chocolatey/docs/commit/fe0321f3d8260ed34a2a835e4687cc5b1c4215a3) that adds running npm and gulp into the process, and this is now live, and seems to be working well 😄   Thanks for getting this done!
