### ISSUE TITLE
Docs for Install contains a Broken Short-link

### ISSUE THREAD

**Issue by JPRuskin** [chocolatey/docs#283]
### What I am seeing:

When looking for documentation for [installing a `packages.config` file](https://docs.chocolatey.org/en-us/choco/commands/install), I am directed to the short-link `bit.ly/packages_config`, which directs to a header that no longer exists on the [chocolatey/choco ReadMe.md](https://github.com/chocolatey/choco#packagesconfig).

![image](https://user-images.githubusercontent.com/1975761/139655762-11890917-cdba-4831-b4c7-425afd49659b.png)

### What is expected:

An xref link to [the packages.config section](https://docs.chocolatey.org/en-us/choco/commands/install#packages.config), further down the page, or a link to something that addresses the issue in question (package names ending with .config).
We could also use the https://ch0.co link shortener, instead of bit.ly.

### Steps to Reproduce:

- Navigate to https://docs.chocolatey.org/en-us/choco/commands/install#usage
- Test the link to https://bit.ly/packages_config

**Comment by TheCakeIsNaOH** [comment]
Issue already logged over at choco cli:
https://github.com/chocolatey/choco/issues/2401

**Comment by pauby** [comment]
This is just a part of that @TheCakeIsNaOH - the one over at chocolatey/choco#2401 would deal with the updates to the code.

**Comment by gep13** [comment]
The file in the docs repository is generated from the source code file in the chocolatey/choco repository, so fixing it there, would ultimately fix it here as well.

**Comment by pauby** [comment]
In that case we can close this issue when [this PR is merged](https://github.com/chocolatey/choco/pull/2442).

**Comment by gep13** [comment]
@pauby that PR is merged, but the fix in the docs repository won't be done until we generate the docs from the `chocolatey/choco` repository.

**Comment by ryanrichter94** [comment]
Closing this issue as link in docs now uses ch0.co short URL and links to the correct part of the docs.
