### ISSUE TITLE
Upgrade "Marked" to v4.0.10 or later

### ISSUE THREAD

**Issue by st3phhays** [chocolatey/docs#323]
### What You Are Seeing?
There is a security vulnerability in the version of Marked we are using, and it needs to be upgraded to version 4.0.10 or later in order to resolve this issue. See https://github.com/advisories/GHSA-rrrm-qjm4-v8hf.

### What is Expected?
No security vulnerabilities should be present in choco-theme.

### How Did You Get This To Happen? (Steps to Reproduce)
Notified of this vulnerability by dependabot. I can also run `yarn audit` to see this vulnerability.

**Comment by gep13** [comment]
@st3phhays thanks for getting this fixed up!
