### ISSUE TITLE
Add Intune Configuration Values to Configuration Doc

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/docs#355]
While working on #353 making sure no other config of feature settings were missed I noticed the intune config values are not listed on the page yet. [Config page](https://docs.chocolatey.org/en-us/configuration) for reference. I know these are currently still tied to a preview feature however should I add them to the overall configuration documentation? @pauby

**Comment by pauby** [comment]
We should still add them even if they are under preview. I was absolutely certain this had been done, but I looked at the page, and you are right, they are not there. They are documented, but only on the [Chocolatey Licensed Extension](https://docs.chocolatey.org/en-us/licensed-extension/intune/configuration#configuration-values) page.

Taking CCM as an example, the config settings are documented in both the main [config page](https://docs.chocolatey.org/en-us/configuration) and the [CCM page](https://docs.chocolatey.org/en-us/central-management/usage/service/configuration#chocolatey-configuration-file). So, we should follow that example.
