### ISSUE TITLE
Update readme with information about what this is

### ISSUE THREAD

**Issue by gep13** [chocolatey/docs#42]

**Comment by TheCakeIsNaOH** [comment]
It probably would be a good idea to include the build dependencies as well.

So `yarn`, `nodejs`, `dotnet-something`, maybe something else I already had installed.

**Comment by gep13** [comment]
Yes, it is this sort of information that this issue was intended to catch, along with a few other things.

Hoping to get to this tomorrow.

**Comment by gep13** [comment]
@TheCakeIsNaOH I have just added some details about what is required.

Would be great if you can have a look and let me know if you think there is anything missing.

**Comment by TheCakeIsNaOH** [comment]
@gep13 Perfect, exactly what I was looking for.
