### ISSUE TITLE
Correctly render markdown emojis

### ISSUE THREAD

**Issue by gep13** [chocolatey/docs#43]
Currently, items like `:floppy_disk:` and `:heavy_plus_sign:` are not rendering correctly when generated through Statiq.

There should be a way within Statiq to render these emojis correctly.

**Comment by gep13** [comment]
@designxsteph just wanted to make sure that you saw this...

I have made it so that Statiq renders the emojis, so we don't need to put the unicode version directly into the code.

Thanks to @daveaglick for telling me how to do this!

**Comment by designxsteph** [comment]
@gep13 ah perfect!

**Comment by gep13** [comment]
This was the change that made it work:

https://github.com/chocolatey/docs/commit/4fac17dc38a202130c9b1c1b8eb1438db2b1232c#diff-0b69b473fe937040615d69f606751f61ddbc2e3a1849360ff2456c22afe88c0bR21

The other changes in the commit were just switching away from the unicode version.
