### ISSUE TITLE
Change note that Get-PackageParameters is now available in Chocolatey CLI directly

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/docs#430]
### What You Are Seeing?

https://docs.chocolatey.org/en-us/guides/create/parse-packageparameters-argument

![image](https://user-images.githubusercontent.com/38865330/160498245-83eea496-aa18-49c5-9e37-53d33d67613d.png)

### What is Expected?

`Get-PackageParameters` has actually been available directly as a helper since Chocolatey CLI 0.10.8
https://github.com/chocolatey/choco/issues/1393

The note should be updated.

### How Did You Get This To Happen? (Steps to Reproduce)

N/A

**Comment by Manoj496** [comment]
Hi @TheCakeIsNaOH but it's not working in 0.11.2, it's working after upgrading to latest available. It is skipping the installation to the path given choco install <pkg_id> --params "'/LICENSE:value'"``. eg: choco install <pkg_id> --params "'/customlocation:C:/users/somedir'". But when using the command with latest chocolatey I can see the package installed to the given path.

**Comment by TheCakeIsNaOH** [comment]
@Manoj496 if you are still having issues with using `Get-PackageParameters`, I'd suggest asking in chat: https://ch0.co/community
