### ISSUE TITLE
List Intune on Integrations Page

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/docs#436]
## What New Or Updated Would You Like To See?
Wanna add Intune to our [integrations features page](https://docs.chocolatey.org/en-us/features/integrations). Since it isn't listed anywhere at https://chocolatey.org/compare currently. 

## Why Is It Needed?
Make note of our product integration outside of the setup docs themselves.

**Comment by pauby** [comment]
Just for clarity, there are docs for Intune [here](https://docs.chocolatey.org/en-us/licensed-extension/intune/), and [here](https://docs.chocolatey.org/en-us/third-party-integrations/intune/).
