### ISSUE TITLE
Right sidebar links incorrect if the header contains a link

### ISSUE THREAD

**Issue by designxsteph** [chocolatey/docs#45]
If a header contains a link, the right sidebar links are generated with a "link inside of a link". There needs to be a way to accommodate this edge case.

This can be seen on: https://docs.chocolatey.org/en-us/chocolatey-gui/release-notes

<img width="1359" alt="Screen Shot 2020-11-03 at 7 25 17 AM" src="https://user-images.githubusercontent.com/42750725/97990763-09bba080-1da6-11eb-8692-f7bb8ddf86da.png">

**Comment by designxsteph** [comment]
@gep13 I might need some help with this one. Cant quite figure it out. I can probably find a js solution, but if theres a way in razor/c# I feel like that'd be better.

**Comment by vexx32** [comment]
These strings are short enough that a regex based solution might be sufficient here? https://stackoverflow.com/questions/785715/how-can-i-strip-html-tags-from-a-string-in-asp-net

**Comment by gep13** [comment]
I have been chatting with Dave, and this might be something best solved in Statiq, he has asked that I raise an issue about this to see what can be done.

**Comment by daveaglick** [comment]
I've also got a thought on how to address it in the near-term (until Statiq can be patched) - let me work that up and I'll come back here tomorrow with some code you can add to your own build while I work on the problem upstream.

**Comment by daveaglick** [comment]
Add this to your bootstrapper:

```csharp
.ModifyPipeline(
    nameof(Statiq.Web.Pipelines.Content),
    pipeline => pipeline.ProcessModules.Add(
        new ExecuteConfig(Config.FromDocument(async doc =>
        {
            List<IDocument> headings = doc.GetDocumentList(Statiq.Html.HtmlKeys.Headings).ToList();
            if (headings?.Count > 0)
            {
                for (int i = 0; i < headings.Count; i++)
                {
                    IHtmlDocument htmlDocument = await Statiq.Html.HtmlHelper.ParseHtmlAsync(headings[i]);
                    headings[i] = await headings[i].CloneAsync(htmlDocument.Body.TextContent);
                }
                return doc.Clone(new MetadataItems
                {
                    { Statiq.Html.HtmlKeys.Headings, headings }
                });
            }
            return doc;
        }))))
```

Basically it adds a module that clones documents with heading metadata with new heading metadata that takes the text content (stripping out any HTML) of the heading. The new module is defined inline as an `ExecuteConfig`, but could easily move to a dedicated custom module if you don't want to pollute your bootstrapper setup.

**Comment by gep13** [comment]
I have raised an issues in Statiq.Framework to cover this:

https://github.com/statiqdev/Statiq.Framework/issues/142

**Comment by gep13** [comment]
I have just taken the workaround for a spin, and it looks good:

![image](https://user-images.githubusercontent.com/1271146/98080925-27543d00-1e6e-11eb-86f2-d909eff48e16.png)

@daveaglick thanks for much for doing this!

**Comment by daveaglick** [comment]
💯 keep an eye out for the upstream fix - I plan to address this in the next release and then you can remove the workaround.
