### ISSUE TITLE
Search doesn't appear to look inside of codefences

### ISSUE THREAD

**Issue by corbob** [chocolatey/docs#462]
### What You Are Seeing?

Someone mentioned having issues upgrading in discord, so I tried to find the document regarding fixing `The registered delegate for type IEnumerable<ICommand> threw an exception.` by searching for terms delegate and then ienumerable. The correct result did not appear at all.

### What is Expected?

https://docs.chocolatey.org/en-us/licensed-extension/compatibility#troubleshooting is found as it contains a codefence with that error in it. 

### How Did You Get This To Happen? (Steps to Reproduce)

See above.

**Comment by st3phhays** [comment]
This might be of use: https://discourse.algolia.com/t/experience-and-advice-for-dealing-with-indexing-of-code-in-software-documentation/8307
