### ISSUE TITLE
The guide for creating templates ends abruptly

### ISSUE THREAD

**Issue by corbob** [chocolatey/docs#524]
### What You Are Seeing?

Navigate to https://docs.chocolatey.org/en-us/guides/create/create-custom-package-templates to get information on custom package templates. The page ends abruptly in the middle of a sentence

### What is Expected?

The full page is rendered successfully

### How Did You Get This To Happen? (Steps to Reproduce)

1. Navigate to the page
2. Scroll to the bottom

### Further details

It would appear that this line is the cause: https://github.com/chocolatey/docs/blob/b5a800f575cd4ebab265d0b995549abde6085967/input/en-us/guides/create/create-custom-package-templates.md?plain=1#L114

I would speculate maybe the HTML tag is doing something with Statiq: 

![2022-08-05_11-17-47](https://user-images.githubusercontent.com/30301021/183137605-56293e15-5cd4-4ee7-8cd9-0e5e6035473f.png)

**Comment by corbob** [comment]
Duplicate of #588

**Comment by rsmall-apira** [comment]
@corbob technically my issue was the dupe :)

**Comment by corbob** [comment]
@rsmall-apira this is true, but @pauby already has a pr up tagging yours, and so it seemed easier to close this as dupe than change around the pr 🤷 ultimately as long as it gets fixed.
