### ISSUE TITLE
Add release video for new v1.1.0 release of Chocolatey Agent

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/docs#528]
## What New Or Updated Would You Like To See?

Add a new release video for the upcoming release of Chocolatey Agent v1.1.0

## Why Is It Needed?

Generally, all releases have a video associated with them that goes through what is new and fixed in the release. The new release should also have such a video associated.

## Additional Context?

N/A

**Comment by ryanrichter94** [comment]
Release video for chocolatey-agent V 1.1.0 has been published to docs. Closing off this issue.

**Comment by AdmiringWorm** [comment]
Since it wasn't reference, and so we have a backlink to which commit it was added in.

Video was added in commit 7506b334442a4f7cd7de5d60c3ec83d5c280bef8

**Comment by gep13** [comment]
Apologies, I didn't know that an issue had been created to track this! Thanks for catching this!
