### ISSUE TITLE
Add alternative use for private/internal variable usages

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/docs#553]
## What New Or Updated Would You Like To See?

The rule we currently have about not using private or internal variables does not call out when there are alternatives that can be used.
We should document how it is possible to get similar information using alternative methods.

## Why Is It Needed?

A maintainer may sometimes want to get a piece of information similar to what one of the private/internal variables makes use of. For these maintainers, we should provide an alternative way that they may use.

## Additional Context?

This was called out in our community chat: https://discord.com/channels/778552361454141460/897088817293574154/1022538645862879252.

**Comment by vexx32** [comment]
Confirmed with @AdmiringWorm that the above commits cover the variables that we want to permit folks to use in some fashion with their workarounds, so we can close this one out for now.
