### ISSUE TITLE
Documentation for custom templates cut off on docs.chocolatey.org

### ISSUE THREAD

**Issue by rsmall-apira** [chocolatey/docs#588]
### What You Are Seeing?

The [guide for managing custom templates as packages ](
 https://docs.chocolatey.org/en-us/guides/create/create-custom-package-templates) ends prematurely with the words "To manage a template as a package, create a new package with the name " " 

### What is Expected?

The sentence/paragraph is completed.   I'm guessing it should have the same text as [here](https://github.com/chocolatey/choco-wiki/blob/master/How-To-Create-Custom-Package-Templates.md#manage-as-templates-as-packages)

### How Did You Get This To Happen?
1. Tried to follow the docs to make a custom choco template.

### System Details

* Running Firefox or Edge browsers in Windows 11

**Comment by pauby** [comment]
I've submitted #589 to fix this.
