### ISSUE TITLE
Implement a search mechanism

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/docs#6]
If there is something that we can use for free, let's use that for now. We can look at other options later.

**Comment by gep13** [comment]
@designxsteph I have just merged in the PR to implement the basics of the Algolia search box.  There is some additional information on styling that can be achieved here:

https://docsearch.algolia.com/docs/styling/

And the search configuration is hosted here:

https://github.com/algolia/docsearch-configs/blob/master/configs/chocolatey.json

If we need to make any tweaks to it.
