### ISSUE TITLE
Expand documentation on hook scripts

### ISSUE THREAD

**Issue by pauby** [chocolatey/docs#601]
## What New Or Updated Would You Like To See?

The documentation on hook scripts needs to be expanded. See this [issue comment](https://github.com/chocolatey-community/chocolatey-hooks/issues/6#issuecomment-1327115561) for a good starter on this.

## Why Is It Needed?

It's clear that people know about or know how to use, hook scripts.

## Additional Context?

N/A

**Comment by TheCakeIsNaOH** [comment]
As per [this comment](https://github.com/chocolatey-community/chocolatey-hooks/issues/6#issuecomment-1328049705), make sure to include information about `--skip-hooks`

**Comment by steviecoaster** [comment]
@pauby I've picked this up.
