### ISSUE TITLE
no Installing !

### ISSUE THREAD

**Issue by ramiljs** [chocolatey/docs#625]
Hello
I installed openjsk11 with Chocolate, in cmd there is a message that it is installing, but it is not installed!

![Снимок](https://user-images.githubusercontent.com/89657343/208225470-47ae3972-e2d1-43e4-973e-d86f937ff9ac.PNG)

**Comment by pauby** [comment]
This is the wrong place to raise this issue. Please raise the issue with the maintainer by clicking the 'Contact Maintainers' link on the package page or go to [Discord](https://ch0.co/community) and ask there.
