### ISSUE TITLE
CMD + K focuses on search box, but if click off and then press only Cmd, it will refocus (chrome on Mac OS)

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/docs#63]
This is an interesting issue - seems like K isn't required to refocus on the search box after the first time.

**Comment by ferventcoder** [comment]
This is cmd or Ctrl, depending on platform.

**Comment by pascalberger** [comment]
Don't know if this is some a bug or not. Ctrl+K no longer moved the focus into the search box when I just recently tried (Firefox, Windows), but suddenly after a few retries is started to work and I no longer can reproduce it.

**Comment by designxsteph** [comment]
I've been doing some testing on this. Seems to only happen on Mac OS in Chrome, unless someone can confirm this happening on Windows as well (or additional browsers). I've also updated the title since the code has changed a bit and is no longer in a modal.

**Comment by designxsteph** [comment]
> Don't know if this is some a bug or not. Ctrl+K no longer moved the focus into the search box when I just recently tried (Firefox, Windows), but suddenly after a few retries is started to work and I no longer can reproduce it.

I can confirm some weirdness going on with this in Firefox as well. Thanks for the heads up!

**Comment by gep13** [comment]
@pascalberger I have just pushed out a new version of the site which hopefully addresses the issue that you noticed.  Would you mind taking the site for a spin again, and let me know if you are still seeing problems?  Thanks

**Comment by pascalberger** [comment]
@gep13 Couldn't really reproduce it before, so no guarantee, but I tried on two machines and it worked on both

**Comment by pascalberger** [comment]
Don't know if you see this as a bug or feature:

* Go to docs.chocolatey.org using Firefox
* Ctrl+K
* Search box is now focused
* Ctrl+K
* Browser search box is now focused
