### ISSUE TITLE
Remove docs site version, include SHA and link to codebase

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/docs#64]
At the bottom of the docs site you'll see "Copyright 2020 Chocolatey Software", then something like "0.0.0-preview.0.143". See image below:

![image](https://user-images.githubusercontent.com/63502/99317738-22a76580-282c-11eb-8914-a65adb97cca4.png)

We don't version this site, so I would prefer instead to see a Git SHA with a link back to this codebase. This is what we do on the Chocolatey.org site (even though the text is hidden by default). See image below: 
 
![image](https://user-images.githubusercontent.com/63502/99317895-61d5b680-282c-11eb-8ec1-30df942d4ac6.png)

I don't think we need to hide the text, but it should be using the SHA if we are going to show anything.

**Comment by gep13** [comment]
I am going to modify this to the following:

![image](https://user-images.githubusercontent.com/1271146/99373122-f554c900-28b8-11eb-8ad4-4f5ecce1ad8a.png)
