### ISSUE TITLE
Put Deprecation Warning On Current QDE Docs

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/docs#642]
## What New Or Updated Would You Like To See?

Add a Warning to the top of all current QDE documentation. This warning should let people know QDE is deprecated and to instead reference the quick start guide.

## Why Is It Needed?

Sometimes get asked if we offer the QDE solution. Also it is not mentioned in its documentation currently that is deprecated. 

## Additional Context?
NA

**Comment by pauby** [comment]
Can you update the issue with the template?
