### ISSUE TITLE
`--install-arguments-sensitive` and `--package-parameters-sensitive` not available in free version.

### ISSUE THREAD

**Issue by fardarter** [chocolatey/docs#647]
Just here to register my dislike of this choice. Tool security should never be a paid feature.

**Comment by gep13** [comment]
@fardarter I have taken the liberty to edit your comment in this issue or remove the unnecessary and inflammatory language.

While I can understand that you may not agree with the decision to include that feature in the open source version of Chocolatey, the way that you have expressed the concern isn't helpful to anyone.

In addition, the docs repository is not the correct place to discuss this matter.  If you wanted to discuss this further, I would suggest that you open a [discussion](https://github.com/orgs/chocolatey/discussions) or reach out on our [Discord Server](https://ch0.co/community).

If you do decide to continue the discussion, I would request that you read through the [Code of Conduct](https://github.com/chocolatey/.github/blob/main/CODE_OF_CONDUCT.md) for our community, and be respectful to other members of the community.

With all of the above stated, I am going to go ahead and close off this issue.
