### ISSUE TITLE
Typos in docss

### ISSUE THREAD

**Issue by stefansjfw** [chocolatey/docs#678]
### What You Are Seeing?
Typos in docs on page https://docs.chocolatey.org/en-us/features/powershell
<img width="850" alt="image" src="https://user-images.githubusercontent.com/57057282/226138621-4575d646-0df9-4177-a3a4-4ee505ae5500.png">

### What is Expected?
No typos.

### How Did You Get This To Happen? (Steps to Reproduce)
Open the page and read the docs.

**Comment by gep13** [comment]
@stefansjfw thank you for noticing this, and for raising this issue! Would you be in a position to follow up with a PR to correct the problem?

**Comment by stefansjfw** [comment]
Sure thing. Here it is: https://github.com/chocolatey/docs/pull/679
