### ISSUE TITLE
Link to #manage-chocolatey-installation broken

### ISSUE THREAD

**Issue by superbonaci** [chocolatey/docs#778]
This page:
https://docs.chocolatey.org/en-us/choco/setup#completely-offline-install

Has a link that does not exist anymore:
https://forge.puppet.com/puppetlabs/chocolatey#manage-chocolatey-installation

**Comment by LeaDevelop** [comment]
You can assign this issue to me url changed to:
`https://forge.puppet.com/modules/puppetlabs/chocolatey/readme#manage-chocolatey-installation`
