### ISSUE TITLE
Document version number normalization

### ISSUE THREAD

**Issue by corbob** [chocolatey/docs#789]
## What New Or Updated Would You Like To See?

Add a page to the documentation explaining Version number normalization.

## Why Is It Needed?

With the upgrade to V2, version numbers are normalized. Currently we only explain this on the migration guide, but we should explain this on it's own page as it will exist beyond the initial migration.

## Additional Context?

https://github.com/chocolatey/docs/pull/764#discussion_r1268279821

**Comment by pauby** [comment]
We should update the link mentioned in that [comment](https://github.com/chocolatey/docs/pull/764#discussion_r1268279821), once we create the page.
