### ISSUE TITLE
Nexus does not allow a v2 and v3 feed in the same proxy group

### ISSUE THREAD

**Issue by pauby** [chocolatey/docs#790]
## What New Or Updated Would You Like To See?
When we talk about creating a proxy group in Nexus, we should clarify that a Nexus proxy group cannot have both v2 and v3 feeds in the same group. See this [Discord thread](https://discord.com/channels/778552361454141460/897097047801475103/1131342646271549572)

## Why Is It Needed?
This is really more of an understanding Nexus than working with Chocolatey issue, but with the introduction of v3 feeds in Chocolatey CLI 2.0.0, but CCR not currently supporting them, it may get a little confusing. 

## Additional Context?

[Discord thread](https://discord.com/channels/778552361454141460/897097047801475103/1131342646271549572).

![image](https://github.com/chocolatey/docs/assets/12760779/a6c2edf6-4d24-4b58-abe3-c657d062a145)

**Comment by TheCakeIsNaOH** [comment]
Here is the Nexus documentation page, which does confirm that they explicitly do not support having v2 and v3 feeds in the same group: https://help.sonatype.com/repomanager3/nexus-repository-administration/formats/nuget-repositories/grouping-nuget-repositories

**Comment by pauby** [comment]
Looking through the documentation I can't actually find anywhere where we talk about a Nexus group / virtual repository that this documentation would be relevant to.

@imm0rtalsupp0rt @ryanrichter94 @JPRuskin @gep13 (or anybody else) got any thoughts where this would be relevant to add?

**Comment by ryanrichter94** [comment]
@pauby Might wanna add it as a note in the [NuGet V3 Section](https://docs.chocolatey.org/en-us/guides/upgrading-to-chocolatey-v2-v6#nuget-v3-feed-support-added) of the Upgrade Guide for Chocolatey V2. This to my knowledge is where we try to call out any breaking changes as best we can with going to the new features offered in Chocolatey V2.
