### ISSUE TITLE
defaultPushSource Missing From Configuration Doc

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/docs#801]
### What You Are Seeing?
The defaultPushSource configuration option is not documented on our [Configuration Docs Page](https://docs.chocolatey.org/en-us/configuration#config-settings) 

### What is Expected?
This should document all know options in Chocolatey CLI

### How Did You Get This To Happen? (Steps to Reproduce)

1. Browse to the current [Configuration Docs Page](https://docs.chocolatey.org/en-us/configuration#config-settings)
2. defaultPushSource is not listed on the page.

**Comment by gep13** [comment]
This is a duplicate of this issue: https://github.com/chocolatey/docs/issues/796 I noticed the same thing 😄

**Comment by ryanrichter94** [comment]
Closing as duplicate issue. Thanks @gep13
