### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by HOAMTH** [chocolatey/docs#807]
### What You Are Seeing?
Any queries made with choco fail with the same error everytime: "The request was aborted: Could not create SSL/TLS secure channel." I ran the same command with and without --debug and --verbose. See here: https://gist.github.com/HOAMTH/1b0380c9e3e2d7402e03bd7af089bd1c
(Oddly, decypting HTTPS with Fiddler makes it work properly...)
### What is Expected?
Return the matching packages.

### How Did You Get This To Happen? (Steps to Reproduce)
Install chocolatey using the install script from the website with the bypass.
Close and reopen Powershell.
Run "choco search chocolateygui".

**Comment by pauby** [comment]
@HOAMTH This is the documentation repository. If this is an issue with Chocolatey CLI, can you check for similar issues and raise it over at https://github.com/chocolatey/choco/issues ?
