### ISSUE TITLE
Complexity of install commands makes "simpler" command... not, really.

### ISSUE THREAD

**Issue by ferdnyc** [chocolatey/docs#848]
[`input/en-us/choco/setup.md`](input/en-us/choco/setup.md) contains two different versions of the PowerShell install command.

§[Installing with PowerShell.exe](https://github.com/chocolatey/docs/blob/master/input/en-us/choco/setup.md#install-with-powershellexe) has:

> ```powershell
> Set-ExecutionPolicy Bypass -Scope Process -Force;
> [System.Net.ServicePointManager]::SecurityProtocol = 
> [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
> iex ((New-Object System.Net.WebClient).DownloadString(
> 'https://community.chocolatey.org/install.ps1'))
> ```

Whereas, showing a stunning command of irony, §[Install from PowerShell v3+](https://github.com/chocolatey/docs/blob/master/input/en-us/choco/setup.md#install-from-powershell-v3) offers:

> The command for installing with PowerShell at the top of the page works for all versions of PowerShell from v2 on. This is provided as an additional note for folks who want a more terse command that is easier to remember.

That command?

> ```powershell
> Set-ExecutionPolicy Bypass -Scope Process -Force;
> [System.Net.ServicePointManager]::SecurityProtocol = 
> [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
> iwr https://community.chocolatey.org/install.ps1 -UseBasicParsing | iex
> ```

I suppose it's _technically_ true that the command is "more terse". **Slightly.** But, "easier to remember"? `¯\_(ツ)_/¯`

_Originally posted by @ferdnyc in https://github.com/chocolatey/docs/pull/847#discussion_r1339318323_

**Comment by ferdnyc** [comment]
(For context, [way back when](https://github.com/chocolatey/choco-wiki/blob/b9d9063b87d43a5b948ccc0162f3434cbc4c9e51/Installation.md), the command choices were between:

```powershell
# Don't forget to ensure ExecutionPolicy above
iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
```

and the "more terse and easier to remember"...

```powershell
iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
```

In _those_ forms: fair. But that was in 2017, and since then the command complexity has grown to make the PowerShell v3+ alternative pretty much pointless.

**Comment by pauby** [comment]
@ferdnyc The sarcasm makes it difficult to understand what you are asking for here. Can you remove that and be very clear about what your issue is? Can you also amend your issue title to be clear about what the issue is about?
