### ISSUE TITLE
Add custom 404 page

### ISSUE THREAD

**Issue by gep13** [chocolatey/docs#88]
This should allow us to better track problems with missing/moved pages.

As per the GitHub pages docs here:

https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site

Related issue here:

https://github.com/chocolatey/blog/issues/24

**Comment by ferventcoder** [comment]
This looks good. You can likely close this?

**Comment by gep13** [comment]
@ferventcoder while this "works", I was still looking for feedback on the wording that is currently in place.  I did ask for feedback via Slack, but this may have been missed.

Currently the wording is:

```
We were unable to find this page. This could be as a result of the recent changes to the site, where we have moved some files around. Please verify that the link you are using is what you expect, or please try searching for the page you are looking for in the search box above. If you are still having problems, please reach out to the Chocolatey Team, and we will do our best to fix this problem.
```

Which is rendered as:

![image](https://user-images.githubusercontent.com/1271146/101882792-41c8b700-3b8e-11eb-8ba2-329998a70746.png)

Still not clear on _where_ we want folks to reach out.  Is it via an issue here, or somewhere else.  If an issue, what should be done about the equivalent page on the blog site?

**Comment by gep13** [comment]
@ferventcoder there was also this comment in another issue:

> Agreed with Paul on the above. And if we can custom the 404 to maybe ask folks to try the link with lowercase if it detects they are using uppercase (or get smart somewhere and try to handle this aspect for them and if that doesn't work to lowercase the path, then show them the 404).

Regarding making the 404 page smarter.

**Comment by st3phhays** [comment]
A custom 404 page has been added, closing this as it has been fixed.
