### ISSUE TITLE
CCM documentation unclear/conflicting on the Windows Minimum OS requirement

### ISSUE THREAD

**Issue by vexx32** [chocolatey/docs#881]
### What You Are Seeing?

The CCM minimum operating system version requirement differs depending on which page we're referring to:

- [Website Setup page](https://docs.chocolatey.org/en-us/central-management/setup/website) - Windows Server 2016
- [Database Setup page](https://docs.chocolatey.org/en-us/central-management/setup/database) - doesn't state a minimum OS version
- [Service Setup page](https://docs.chocolatey.org/en-us/central-management/setup/service) - Windows Server 2019
- [Overall CCM Setup page](https://docs.chocolatey.org/en-us/central-management/setup/) - Windows Server 2016

### What is Expected?

I _think_ the correct route here is either to remove the individual packages' Windows Server requirement notes, or to just update them all to say the same as the overall setup page. We have all CCM packages being tested on 2016 _and_ 2019 at the moment, so the Service setup page is just totally incorrect.

Probably removing the individual package page's Windows Server requirements and linking back to the main Setup page's overall requirements section instead is likely the right move.

/cc @pauby

**Comment by pauby** [comment]
> Probably removing the individual package page's Windows Server requirements and linking back to the main Setup page's overall requirements section instead is likely the right move.

I would suggest this is the correct way to go:

1. Create a single section in a page with the minimum requirements. 
2. Point all other pages to the above section.
 
This means we have one place to update the system requirements if necessary.
