### ISSUE TITLE
External link in setup.md returns a 404 response

### ISSUE THREAD

**Issue by ncarlson** [chocolatey/docs#939]
### What You Are Seeing?

There's an external link in [choco/setup.md][erroneous setup page] that returns a 404. The link text and URL are "administrative shell" and `http://www.howtogeek.com/194041/how-to-open-the-command-prompt-as-administrator-in-windows-8.1/`, respectively. See line [#31 of setup.md][erroneous setup page]

As an aside, many browsers will automatically replace an 'http' link with 'https'. The markdown file points to an 'http' link. The 'https' version of this link returns a 301. However, that 301 redirects to 404.

### What is Expected?

I'd expect that the link in question not return a 404. Additionally, I'd expect there to be instructions on how to open an admin prompt for all supported versions of Windows, if the instructions significantly differ.

For a quick fix, this link might be a good replacement: `https://www.howtogeek.com/194041/how-to-open-the-command-prompt-as-administrator-in-windows-10/`

### How Did You Get This To Happen? (Steps to Reproduce)

1. Open a web browser and navigate to the following URL: https://docs.chocolatey.org/en-us/choco/setup#installing-chocolatey-cli
2. Click on the link text which reads, "administrative shell". This is found under "_1. First, ensure that you are using an administrative shell._"
3. Observe the 404 page.

To verify the response code, do the following:
1. Open a command prompt or terminal, and verify that the links in question return a 404 response.
 1.1 `curl -L -I http://www.howtogeek.com/194041/how-to-open-the-command-prompt-as-administrator-in-windows-8.1/`
 1.2 `curl -I https://www.howtogeek.com/194041/how-to-open-the-command-prompt-as-administrator-in-windows-8.1/`
2. Observe the following response in both cases: `HTTP/1.1 404 Not Found`.

### Other comments

This is slightly outside the scope of this ticket, but there might be value in putting the markdown files through a link response-code linter.

[erroneous setup page]: https://github.com/chocolatey/docs/blob/6e2b31f65ffc4c0e512be034970a29f8d4c9c188/input/en-us/choco/setup.md?plain=1#L31

**Comment by pauby** [comment]
Thanks, @ncarlson, for catching that. I've raised PR #942 to fix this.
