### ISSUE TITLE
Package Triage Process needs updated as to new processes

### ISSUE THREAD

**Issue by pauby** [chocolatey/docs#99]
This stemmed from a discussion on [Google Groups](https://groups.google.com/d/msg/chocolatey/cytXjxLFlhs/Gj8IXwLXBQAJ).

The processes now followed are different to those documented and we need to update them.

**Comment by gep13** [comment]
@TheCakeIsNaOH I have moved this issue from the wiki repository to here, and I have updated to PR to reference this issue.
